include/enoki/array_traits.h
include/enoki/jit.h
include/enoki/vcall.h
include/enoki/vcall_autodiff.h
include/enoki/vcall_jit_record.h
tests/vcall.cpp

This PR seperated the pointer registry datastructures for the LLVM and CUDA backends.

Seperate registry for LLVM and CUDA backends

---

enoki/matrix.py
include/enoki/quaternion.h
tests/python/test_matrix.py

This PR introduces a fix to the quaternion to Euler angles conversion code to handle gimbal lock properly. A unit test (on the python side) has also been added, with conversion values determined in Matlab.
The reverse conversion Euler -> Quaternion has also been implemented.

Gimbal Lock in Quaternion -> Euler angles conversion

---

include/enoki/tensor.h
tests/python/test_tensor.py

The result of all select operations on Tensor types was accidentally being cast to integer.
Also adds a unit test covering this bug.

Tensor: fix `select` return type

---

src/python/tensor.h

The Tensor constructor from a Python object checks whether that object makes available an `__array_interface__` with `hasattr()`.
But `hasattr()` actually *executes* the `__array_interface__` property in order to determine whether it is available (https://stackoverflow.com/a/30143990/3792942)
If the Python object was an Enoki array, in many cases, `__array_interface__` actually needs to migrate the array to the host to make its data available.
This lead to many accidental migrations to host memory when constructing tensors from other Enoki arrays.
Ideally, we could find a way to allow `hasattr` while avoiding actual migrations, but in the meantime this fix simply avoids the `hasattr` call for Enoki arrays.

Tensor: fix accidental migrations due to `hasattr()`

---

include/enoki/texture.h
src/python/texture.h
tests/texture.cpp

The PR has two new functions ("eval_cubic", "eval_cubic_grad") and some tests.
It supports (cuda-texture/enoki based) (1/2/3D) cubic b-spline fitting with (1/2/4 channels). 
Both _grid data_ and _query position_ have differentiable support.
The function "eval_cubic_helper" is an internal function.

[texture] cubic bsp support

---

include/enoki/texture.h
src/python/main.cpp
src/python/texture.h
tests/texture.cpp

This PR adds a `WrapMode` `enum` to extend the possible texture wrapping modes with: clamping, repeating.
The `WrapMode` is used both by the `eval()` (`eval_cuda()` and `eval_enoki()`) method with the existing filtering methods, as well as all the cubic spline interpolation methods (`eval_cubic()`, `eval_cubic_helper`, `eval_cubic_grad`).
Tests cover the new wrapping modes in all aforementioned methods, for 1, 2 and 3 dimensional textures.
Notes:
I do not know the fine details of the current & future cubic spline interpolation methods use cases, but it seems to me like we could expose them through an unified interface by adding a `CubicSpline` variant to `FilterMode`. Alternatively we maybe should/could add a warning when using the cubic spline interpolation methods with the `FilterMode` …

Texture: add clamp and mirror wrapping modes

---

include/enoki/texture.h
tests/texture.cpp

The move constructor and the move assignment operator would not even compile :sweat:
This PR fixes both methods and adds rudimentary tests cases which should at least guarantee that they compile.

Texture: fix move semantics

---

include/enoki/texture.h
src/python/texture.h
tests/texture.cpp

Simple implementation of `eval_cubic_hessian()`.
Compatible with Nicolas's changes about wrapping mode and others.
- It returns **both positional "gradient" and "hessian"**. 
They have quite some common computation. But consequently there is no interface to compute only the "hessian".
The return type is a ~`std::tuple`~`std::pair`.
- Now all the gradients/hessian return value has **the volume resolution** multiplied.
Prior to this PR, we assume the volume has unit size (because the query point is in [0, 1]^d). I need to manually multiply the shape with the returned "gradient" in my volume optimization.
But this becomes too complicated for "hessian" matrix, where each cell needs a different multiplier. So I moved this "unit size -> volume shape transformation" jacobian inside.
This change …

Cubic bspline hessian matrix & resolution update

---

include/enoki/texture.h
src/python/texture.h
tests/texture.cpp

With this PR `enoki::Texture` can now handle textures with an arbitrary number of channels.
All evaluation interfaces were changed, they now take an output parameter that is used to write the evaluation's result to. The python bindings for the evaluation methods still directly return the result, however these are now returned as python list of length N for a N-channel texture.
Tests were added to cover the new interfaces and verify the underlying implementation in `enoki-jit` when using CUDA texture objects.
:warning: This PR is already rebased on Ziyi's work in https://github.com/wjakob/enoki/pull/23 (not merged yet).

Texture: add support for N-channel textures

---

include/enoki/texture.h
src/python/texture.h
tests/texture.cpp

This PR adds `eval_fetch_enoki()`, `eval_fetch_cuda()` and `eval_fetch()`. These methods fetch the texels referenced in the linear interpolation of a given lookup position. 
`eval_fetch_cuda()` makes use of specific PTX instructions for 2D textures. For 1D and 3D textures, the method performs a normal texture lookup (`eval_cuda()`) at the center of every needed texel.
New tests are added for these methods. They cover gradient computations, GPU migration behaviors, and expected outputs in 1D/2D/3D.
***
Bug fixes & others:
- Fixes a bug in `eval_cubic` where the output could be wrong for textures with more than one channel.
- Modifies all methods where the access/traversal pattern did not correspond to the underlying storage layout of the texture data.

Texture: add methods to fetch texels referenced in linear interpolation

---

drjit/__init__.py
resources/generate_stub_files.py
src/python/CMakeLists.txt

This PR is somewhat of a followup to this issue: https://github.com/mitsuba-renderer/mitsuba3/issues/228
Currently, `drjit` has a `os.add_dll_directory` statement in its `__init__.py` file. Unfortunately, this functionality is not well supported by Conda on Windows (https://github.com/conda/conda/issues/10897). Moreover, this code is only useful when building **Mitsuba** and serves no purpose when using Dr.Jit on its own.
This PR removes the `os.add_dll_directory` statement.
This PR also refactors the Python stub file generation such that it expected the `drjit` package to already be located on the `PYTHONPATH`. This is not a necessary change, but rather for consistency with the work done in https://github.com/mitsuba-renderer/mitsuba3/pull/245.

Remove additional DLL search directories in Python package init

---

drjit/router.py
tests/python/test_wrap_ad.py

When using `wrap_ad` I noticed that the following would fail if you ran `dr.backward()` afterwards:
```
@dr.wrap_ad(source="drjit", target="torch")
def torch_func(x: List[torch.Tensor]):
return x[0]
```
Previous assumption supposed that arguments had flattened `torch.Tensor` allowing it to just query `grad` in element of `args` . Therefore, it tried to query the attribute `grad` from a list, instead of trying to querying it from the element of the list.
We propose a recursive solution that should work for nested list/dict

Support list/dict when wrapping function in wrap_ad

---

drjit/router.py
drjit/traits.py
tests/python/test_wrap_ad.py

`torch.autograd.backward` only supports list of tensors: https://pytorch.org/docs/stable/generated/torch.autograd.backward.html . This causes the previous assumption to break as `self.res_torch` could be a nested structure.
We propose to recursively flatten eveything to be passed to the backward step. We also add a test demonstrating that it works.

Allows functions in `wrap_ad` context to return nested structures

---

include/drjit/vcall.h
tests/vcall.cpp

The mask argument passed to a virtual function call was ignored in the backward/forward pass. This is because all arguments are placed into `std::pair<>` which wasn't properly handled in the routine that tries to extract the mask for the list of arguments.

Fix masked vcall with autodiff

---

include/drjit/loop.h
include/drjit/vcall_jit_record.h
include/drjit/vcall_jit_reduce.h
src/autodiff/autodiff.cpp
tests/ad_megakernel.cpp

This commit contains the Dr.Jit part of two related PRs (with the Dr.Jit-Core part being at https://github.com/mitsuba-renderer/drjit-core/pull/32)
It bundles several improvements to the mask stack. For context, the mask stack is an implicit stack of masks, whose top element is automatically applied to memory reads/writes and a few other operations to disable inactive entries of the current wavefront. That is important because undefined behavior resulting from unmasked memory operations could cause inconsistencies or even crash the program.
LLVM has an implicit default mask (even when the stack is empty) that is needed because the wavefront size might not be an exact multiple of the SIMD vector width. This means that some elements are always masked even in the absence of conditional …

Mask stack improvements

---

include/drjit/jit.h
include/drjit/loop.h

This commit adapts the Dr.Jit repository to API changes in Dr.Jit-Core PR https://github.com/mitsuba-renderer/drjit-core/pull/38 (merged internal and external reference counts).
On the other hand, no changes are needed for PR
https://github.com/mitsuba-renderer/drjit-core/pull/39 due to the abstractions in `include/drjit-core/state.h`

Adaptations to drjit-core API changes

---

include/drjit/vcall_jit_record.h
src/python/switch.h

This patch forces the JIT scope to be set between the tracing of each VCall to deal with the case of symbolic loops within vcalls.

Fix vcall scoping when symbolic loop in vcalls

---

drjit/matrix.py
drjit/router.py
tests/python/test_matrix.py
tests/python/test_quaternion.py

If I have a simple `mi.Quaternion4f q` in Python, the matrix type is not correctly derived when calling `dr.quat_to_matrix(q)`.

Fix array shape in dr.quat_to_matrix

---

include/drjit/tensor.h

The original code will fail on multipling two tensors of shape (512,512,4) and (1,1,4) because of the wrong recursive direction in the for loop.

fix bug in tensor broadcasting

---

drjit/detail.py
drjit/router.py
src/python/switch.h
tests/python/test_switch.py

This patch fixes various issues with `dr.switch` and `dr.dispatch` when the functions have an implicit dependency to variables that have gradient tracking enabled. This was not previously tested, but it is a crucial functionality that needs to be incorporated. Additionally, this PR adds the related unit tests.

Fix implicit gradient tracking in dr.switch and dr.dispatch

---

drjit/router.py
tests/python/test_ad.py

This PR fixes `dr.backward_from` and `dr.formward_from` when used on special types (`IsSpecial == True`).
The current behavior of these functions is to set the gradients to 1 and then propagate them. This first step is complex for certain types, as a gradient of one should be set to all components of the type. This is currently not the case, this PR applies the necessary changes.
Note: This change is specific to `backward_from` and `forward_from`. It seems tempting to fix this in `set_grad` but this could lead to misleading behaviors. For example, let's consider the case of setting the gradient of a quaternion with a single scalar value. We would want to preserve the following equivalence: `dr.set_grad(quat, 1) := dr.set_grad(quat, mi.Quaternion4f(1))`. Neither sides of this equality is …

Fix `dr.backward_from`/`dr.foward_from` on special types

---

include/drjit/array_router.h

In Python we could do something like
```
with dr.scoped_set_flag(dr.JitFlag.LoopRecord, False):
...
```
Adding an equivalent in cpp
```
{
dr::scoped_set_flag scope(JitFlag::LoopRecord, false);
...
}
```

Add scoped_set_flag cpp counterpart which already exists in Python

---

drjit/matrix.py
tests/python/test_matrix.py

This adds support for the following matrix operations/functions on JIT types:
* `dr.transform_decompose()`
* `dr.transform_compose()`
* `dr.quat_to_euler()`
* `dr.euler_to_quat()`
Fixes #177 
The existing tests were modified such that they no longer only cover the scalar types.

Add missing support for JIT types in certain matrix operations

---

include/drjit/autodiff.h
include/drjit/jit.h

This PR just adds the `const` modifier to the definitions of the function `block_sum` inside `jit.h` and `autodiff.h` that were missing previously.

Missing const modifier in block_sum functions

---

include/drjit/array_utils.h

This PR addresses #188 that `mulhi_scalar()` is missing when it's called within `array_utils.h`:
https://github.com/mitsuba-renderer/drjit/blob/c71ebb792c88abf2460e296e213cbcb8069388a8/include/drjit/array_utils.h#L293
which was previously defined in Enoki's [array_fallbacks.h](https://github.com/mitsuba-renderer/enoki/blob/2a18afa2402e0677887c8439fa3d6a270ea15726/include/enoki/array_fallbacks.h#l339-L383).

Add missing mulhi_scalar()

---

drjit/router.py
tests/python/test_wrap_ad.py

This pull request fixes an issue with the `wrap_ad` function when dealing with integer PyTorch tensor arguments. The internal routine responsible for reshaping the gradient tensors was failing as integer tensors don't produce any gradients. 
This fix has been tested and verified to work correctly.
Moreover, this PR adds the ability to specify the `source` and `target` directly passing the module. Here is an example:
```python
import torch
import drjit as dr
dr.wrap_ad(source=torch, target=dr)
def my_func(args):
...
```

Fix and improve dr.wrap_ad

---

drjit/generic.py

There is a small bug when converting Matrix43f (e.g., an RGB Mueller matrix) to NumPy.
In the current master, such a conversion doesn't quite work. Printing an identity matrix produces the following output:
```
>>> import drjit as dr
>>> import numpy as np
>>> print(np.array(dr.llvm.ad.Matrix43f(1.0)))
[[[[1. 0. 0. 0.]
[1. 0. 0. 0.]
[1. 0. 0. 0.]
[0. 0. 0. 1.]]
[[1. 0. 0. 0.]
[1. 0. 0. 0.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]]
[[1. 0. 0. 0.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]
[0. 0. 0. 1.]]]]
>>> 
```
But it should be 
```
[[[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]]
[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]]
[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]]]]
```
This commit fixes this by slightly generalizing the existing stride recomputation.

Fixes the conversion of Matrix43f and similar types to NumPy

---

include/drjit/vcall_jit_record.h

Here is the code with problem:
```c++
#include <iostream>
#include <drjit/jit.h>
#include <drjit/autodiff.h>
#include <drjit/vcall.h>
namespace dr = drjit;
using Float  = dr::DiffArray<dr::LLVMArray<float>>;
struct Base {
virtual Float eval(Float input) const = 0;
Base() { }
virtual ~Base() { }
DRJIT_VCALL_REGISTER(Float, Base)
};
using BasePtr = dr::replace_scalar_t<Float, Base *>;
struct Deri0 : public Base {
Float a = Float(2);
Deri0() = default;
Float eval(Float input) const override {
return input * a;
}
};
struct Deri1 : public Base {
Float a = Float(1);
Float b = Float(5);
Deri1() = default;
Float eval(Float input) const override {
return input * b - a;
}
};
DRJIT_VCALL_BEGIN(Base)
DRJIT_VCALL_METHOD(eval)
DRJIT_VCALL_END(Base)
int main(){
jit_init((uint32_t) JitBackend::LLVM); …
```

fix bug in wrap_vcall() in vcall_jit_record.h

---

drjit/matrix.py

When calling `dr.trace` on an array of matrices, the current implementation accumulates the diagonal entries into an array that is a *reference* to the first diagonal entry. As a consequence, the first entry of the matrix is modified after running this operation.
This issue concerns all vectorized variants.
This PR fixes this by accumulating the result in a new array.
```python
import drjit as dr
M = dr.cuda.Matrix3f(1.)
print(M)
#[[[1.0, 0.0, 0.0],
t = dr.trace(M)
print(M)
#[[[3.0, 0.0, 0.0],
```

dr.trace: Avoid modifying the matrix entries

---

docs/reference.rst
src/python/dlpack.cpp
src/python/docstr.h

Motivated by #198 , extending the dlpack interface to support the stream argument. This can be specified by the consumer (PyTorch, JAX) to inform the producer (Dr.Jit) which stream will be used and requests the producer performs any necessary synchronization.
Within the context of CUDA, as specified by the [Python array API standard](https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__dlpack__.html), the stream integer value has a few special values (-1, 0, 1, 2) but otherwise corresponds to the associated CUstream handle. In the latter case, rather than using `jit_sync_thread`, a new operation `jit_cuda_sync_stream` has been added in drjit-core that uses CUDA event synchronization to avoid blocking the CPU thread that would otherwise occur if we used …

DLPack: Support handling of streams

---

include/drjit/util.h

This PR avoid baking the `start_` and `end_` ints into the generated binary search code in JIT mode, and switches to a constant loop title (see #213).

binary_search: fix unnecessary recompilations

---

drjit/tensor.py
tests/python/test_tensor.py

Add the optional flag `align_corners` to upsample.
This is in line with [PyTorch upsample](https://pytorch.org/docs/stable/generated/torch.nn.Upsample.html).
To upsample the following 2D texture (bi-linear interp) to be 5x5
```
[[1 2]
[3 4]]
```
With `align_corners = False` (default), the result is
```
[[1.        1.1000001 1.5       1.9000001 2.0000002]
[1.2       1.3000001 1.7       2.1       2.2000003]
[2.        2.1000001 2.5       2.9       3.       ]
[2.8000002 2.9       3.3       3.6999998 3.8000002]
[3.        3.1000004 3.5       3.9       3.9999998]]
```
With `align_corners = True`, the result is
```
[[1.   1.25 1.5  1.75 2.  ]
[1.5  1.75 2.   2.25 2.5 ]
[2.   2.25 2.5  2.75 3.  ]
[2.5  2.75 3.   3.25 3.5 ]
[3.   3.25 3.5  3.75 4.  ]]
```

upsample align_corners

---

drjit/traits.py

This patch fixes a small typo in the implementation of the `dr.float_array_t` trait.

Fix typo in dr.float_array_t trait

---

docs/cpp.rst
include/drjit/python.h
src/python/bind.cpp

This PR introduces the following changes:
* Fixes such that `bind_array_t<const T*>` works (const qualifiers are lost in casts from nanobind)
* Handling of already bound types in `bind_array_t`
* ~~Project-relative copy paths for Python files in the CMake build~~ replaced by 554458219323cb6e06b60aff927c43393a2eddfc
~~It also updates `drjit-core` to point to: https://github.com/mitsuba-renderer/drjit-core/pull/81~~

Fixes to bindings, and build system

---

drjit/__init__.py
drjit/ast.py
include/drjit/array_base.h
include/drjit/autodiff.h
include/drjit/util.h
src/python/base.cpp
src/python/init.cpp
src/python/meta.cpp

Various changes:
- `allclose` handles inf comparisons
- added `dr.identity`
- handle reinterpreting pointer type as `UInt32`
- handle numpy (or otherwise) scalar arithmetic with JIT array
- `binary_search` fixed
- `copysign` fixed
- fix for initializations of scalar drjit arrays from other scalar drjit arrays
- allow `array & active` on `DiffArray` types
- minor formatting
These are small changes that have been stacking up from @rtabbara  and I. Would be good to get them in before it grows into an ever larger mix of independent fixes.

Various fixes & improvements

---

src/python/slice.cpp
tests/test_arithmetic.py

This PR fixes Python's equivalent to `dr::masked(some_dr_value, mask) += expr`.
Previous code wouldn't properly handle any sort of inplace operation on the masked value. For example:
```
a = dr.cuda.Float([1, 2, 3])
mask = dr.cuda.Bool(False)
a[mask] *= dr.cuda.Float(3)
print(f"{a=}") # Prints [3, 6, 9]
```
(This doesn't only apply to fully-masked operations, but to partial masks too).
The slot `mp_ass_subscript` would correctly produce the underlying `select`. However the `select`'s values were both always the result of the inplace operation, at which point the mask in meaningless. This PR fixes this by returning a copy of the original value in `mp_subscript`.
I think this is only really valid/correct if the masked value is a left-hand side value of the operation. But I cannot think of a …

Allow inplace operations on masked arrays

---

include/drjit/array_router.h
src/extra/call.cpp
src/extra/common.h
src/extra/cond.cpp
src/extra/loop.cpp
src/python/apply.cpp
src/python/apply.h
src/python/autodiff.cpp
src/python/detail.cpp
src/python/detail.h
src/python/docstr.rst
src/python/memop.cpp
src/python/switch.cpp
tests/test_call_ext.py
tests/test_switch.py
tests/test_while_loop.py

This PR fixes various issues in vectorized calls (and some minor orther stuff).
Minor fixes unrelated to calls in:
* 88567877bb7517daa15d83ff463bb341f39e3c7a
* 72741701937ecc81bcad2026a86cba83b9bbb7d4
* ead64a42fa8ed51ed2acfc3070e69bfe2d79480b
Everything else is somehow related to vectorized calls, either only in symbolic mode, or evaluated mode, or for getters or even for`dr.dispatch`/`dr.switch`. It might be easier review this PR by looking at the individual commits as they all are independent fixes. 
Relies on a fix contained in https://github.com/mitsuba-renderer/drjit-core/pull/88

Fixes to vectorized calls

---

include/drjit/quaternion.h

This patch fixes the `dr::euler_to_quat()` which surprisingly had never been tested in C++.

Fix dr::euler_to_quat()

---

.github/workflows/wheels.yml
docs/reference.rst
docs/textures.rst
drjit/__init__.py
include/drjit/array_router.h
include/drjit/array_utils.h
include/drjit/autodiff.h
include/drjit/call.h
include/drjit/jit.h
include/drjit/math.h
include/drjit/packet_intrin.h
include/drjit/python.h
include/drjit/texture.h
src/extra/call.cpp
src/extra/common.h
src/extra/loop.cpp
src/python/base.cpp
src/python/meta.cpp
src/python/texture.h
tests/call_ext.cpp
tests/test_call_ext.py
tests/test_init.py
tests/test_matrix.py
tests/test_memop.py
tests/test_traits.py
tests/test_while_loop_ad.py

This PR backports some commits that were on `master` but were reverted before rebasing on the `nanobind_v2` branch. They are all edge cases that were wrong in the C++ API, none of them were related to the Python API.
This PR also includes various features and fixes:
* Tests for this drjit-core PR: https://github.com/mitsuba-renderer/drjit-core/pull/91
* Changes to the texture API such that it's numerical precision is better behaved
* New types in the bindings used by Mitsuba for polarization
* Fixes for recursive calls, that would previously recurse infinitely during tracing.
* Fixes to symbolic loops when using AD operations inside of them. This fix (commit: https://github.com/mitsuba-renderer/drjit/commit/fe2526627650045b7a34f98fc75474aeda701468) is particularly hacky and I'm open to …

Backport of commits & various new fixes/features

---

include/drjit/array_router.h

~~The `bind_if_array_t<T>` helper is used in https://github.com/mitsuba-renderer/mitsuba3/pull/1216.~~
Edit: no longer needed.

Fix compilation for Clang 19

---

include/drjit/autodiff.h
include/drjit/extra.h
src/extra/autodiff.cpp
src/extra/call.cpp
src/extra/common.h
src/extra/cond.cpp
src/extra/loop.cpp
src/python/autodiff.cpp
src/python/print.cpp
tests/call_ext.cpp
tests/test_call_ext.py
tests/test_if_stmt_ad.py
tests/test_switch.py

This PR is a follow-up to https://github.com/mitsuba-renderer/drjit/commit/fe2526627650045b7a34f98fc75474aeda701468. That original commit only applied to symbolic loops, in this PR I've added a similar fix for calls and conditionals.
In addition, I refactored the isolation scope creation in c++ such that we can easily force it to be marked as symbolic.
The PR contains regressions tests for calls and conditionals (these could not pass prior to this fix).

Fixes for AD traversal inside of symbolic scope

---

src/python/autodiff.cpp
tests/test_autodiff.py

Picked up when running through the tutorials. Suppose we have
```python
opt = mi.ad.SGD(lr=0.25, params=params)
...
y = mi.Float(2.0)
opt['y'] = y  # A copy should be made here
opt['y'] += 1.0
```
Internally, the `Optimizer` `__setitem__` would perform
```python
...
self.variables[key] = dr.detach(value, True)
```
So in the case that value is  not grad-enabled. we still want a copy of the variable to be stored rather than a reference to the original value.

`dr.detach`: Make sure we return copy of gradient disabled variables

---

src/python/autodiff.cpp
tests/test_autodiff.py

- For `detach`, if the transform callback is called then we know it's a Dr.Jit type
- Otherwise, for other types the `transform_unknown` object is returned which by default is the borrowed reference of the passed-in value
- In the case of a scalar Dr.Jit type, we should be performing a copy because otherwise a `move` will zero-out the original variable (e.g. `dr.scalar.Array3f`)
- The other fix to modify `add_generic` (CustomOp input/output variables) revolves around a missing corresponding JIT (primal) index being provided
- This is a problem for tensors, because `apply.cpp::transform` checks whether the transformed length of the underlying transformed array matches the original to preserve the original tensor shape
- Otherwise, the new tensor is flattened
- i.e. we need the JIT index to …

Fix `detach` with nested scalar Dr.Jit types and CustomOp InputOutput fix and CustomOp InputOutput fix

---

include/drjit/color.h

This patch fixes the conditional logic in the color space transformations routine for static arrays.

Fix color.h conditional logic

---

src/python/meta.cpp
tests/test_arithmetic.py
tests/test_promote.py

Motivated by usage of quaternion with `dr.select`. We should be able to support the case where the mask is a vec4 while the other args are quaternions.

`meta_promote`: Handle promotion from vec4 to quaternion

---

src/python/local.cpp
src/python/local.h

This PR fixes a potential cyclic dependency when using dataclasses in `dr.alloc_local`.
The following code snippet would leak
```python
from dataclasses import dataclass
import drjit as dr
if __name__ == "__main__":
@dataclass
class SampleData:
data: dr.llvm.ad.Float
some_float = dr.llvm.ad.Float([1, 2, 3])
default = SampleData(some_float)
sample_data = dr.alloc_local(SampleData, 10, default)
```
The default value and `dtype` information are sources of cyclic dependencies.

Fix potential cyclic dependencies with `dr.alloc_local`

---

src/python/base.cpp
src/python/common.h

This PR adds handling for postponed type hints ([PEP 563](https://peps.python.org/pep-0563/)) on Dr.Jit functions involving a `dataclass`. These are particularly useful when using Mitsuba, as a `dataclass` will most likely be defined before the variant has been set. Here's an example:
```python
from __future__ import annotations
from dataclasses import dataclass
import mitsuba as mi
import drjit as dr
@dataclass
class SampleData:
data: mi.Float # postponed type annotation (invalid before mi.set_variant())
def main():
sample_data = dr.alloc_local(SampleData, 10) # at this point in time `mi.Float` can be resolved
if __name__ == "__main__":
mi.set_variant("cuda_ad_rgb")
main()
```
The implementation relies on `typing.get_type_hints`, which is the [recommended way of resolving type …

Handle postponed type information in dataclasses

---

src/python/bind.cpp
tests/test_tensor.py

The implicit cast predicate for Dr.Jit array types didn't previously handle the case where the target type is a tensor and the source is a sequence (e.g. ndarray)

Handle implicit conversion of ndarray to tensor types

---

drjit/ast.py
tests/test_ast.py

This PR fixes #252.
List comprehensions and other generators define statement-local variables that can never be part of the state loop. This PR guarantees this by ignoring those variables names during the AST traversal of `@dr.syntax`.
I've added a test that isn't much more than a regressions test - it doesn't actually verify that the generator's variables become part of the loop state.
I think this is a fairly safe change @wjakob, but I'm also a bit adverse to introducing more and more handling of these edge cases in `@dr.syntax`

Handle list comprehensions in `@dr.syntax`

---

src/python/dlpack.cpp

Fixes https://github.com/mitsuba-renderer/mitsuba3/issues/1229
Currently, `__dlpack__` and `__dlpack_device__` are potentially inconsistent. This fix favors `jit_cuda_device_raw` over `jit_var_device`, because the latter will throw an error for JIT variables that point to memory regions allocated by other frameworks  (`jit_var_mem_map`).

Make `__dlpack__` and `__dlpack_device__` constistent

---

src/extra/autodiff.cpp
tests/test_autodiff.py

The target of a packet `scatter` operation has a special code path in the AD layer when forward differentiated (`PacketScatter::forward()`): 
* We first accumulate any existing gradients (prior to the `scatter`) on the target
* Secondly, we individually accumulate each of the packet's values' gradients
The first step was using the wrong JIT index to identify the existing gradients on the target.
(The backward traversal looked up the correct JIT index)
I added a simple regressions test.

Fix forward differentiation of packet scatters

---

src/python/base.cpp
src/python/bind.cpp
tests/test_matrix.py

`dr.cross` : Cast return type back to original type
- Use of swizzle operator will return a dr.jit array type. This means for example swizzling a `mi.Vector3f` returns a `dr.*.Array3f`
For implicit conversion predicate from dr.jit types, also check dimensions are compatible
- Previously types such as `Array4f` -> `Matrix4<Color3f>` would return true as we're just simply checking that the first dimension aligns

Swizzle and implicit binding predicate fixes

---

include/drjit/python.h
src/python/base.cpp
tests/test_call_ext.py

This PR fixes the following snippet: 
```python
uint32_values = UInt32(...)
ptr = dr.reinterpret_array(BasePtr, uint32_values)
assert isinstance(ptr, BasePtr)
```
Previously, `reinterpret_array` would return a value of type `UInt32` instead of `BasePtr`.
For this to work we must allow reinterpretations of `T::IsClass` types to (and only to) vectorized `uint32_t` types. In addition, we also cannot rely on `meta_get_type` to figure out the correct return type as it is unaware of any class types that were bound by other libraries (e.g Mitsuba).
I've added a unit test covering this behavior.

Fix `dr.reinterpret_array` to vectorized class pointers

---

include/drjit/packet_sse42.h

Fixes the definition of the `gather_` function in the `packet_sse4.h` file for `X86_AVX2`.

Fix `gather_` definition for packets (avx2)

---

drjit/interop.py
tests/test_wrap.py

Fixes #270
Torch's autograd tracing is disabled inside of custom `Function` objects. This is an issue when there is a chain of nested `dr.wrap` function calls, as the inner functions will not track their gradients correctly. 
This commit forcefully enables gradient tracking just for the function call.

Fix nested uses of `dr.wrap` with torch

---

src/extra/call.cpp
tests/test_call_ext.py

Follow-up to https://github.com/mitsuba-renderer/drjit-core/pull/98

Update drjit-core submodule (fix for vectorized call bounds checking)

---

src/python/init.cpp
src/python/memop.cpp
tests/test_memop.py
tests/test_tensor.py

Fixes #267 by moving the `is_builtin` check and not using `ravel` when input is a single variable.

Fixed tensor initialization creating opaque

---

docs/basics.rst
src/python/base.cpp
tests/test_arithmetic.py

Previously we would allow operations like `array & mask` to zero out certain indices in `array`. This PR adds this functionality again (it was already present in C++, but not in Python).

Allow `&` operator with masks to zero out indices

---

src/python/detail.cpp

The reduce_identity function, is constructing an intermediate variable to initialize the identity element.
With JIT variants, this was constructing an intermediate opaque value via the `init_data` function.
This PR changes the type of the intermediate value from a JIT type to a scalar type, removing the need for the intermediate opaque.
Previously:
```python
In [1]: import drjit as dr
In [2]: dr.set_log_level(dr.LogLevel.Debug)
In [3]: i = dr.detail.reduce_identity(dr.cuda.Float, dr.ReduceOp.Add, 1)
jit_var_new(): float32 r1 = data(<0x302000000>)
jit_var_mem_copy(): float32 r1[1] = copy_from(host, <0x7ffccba48230>)
jit_var_new(): float32 r2 = 0
```
Now:
```python
In [1]: import drjit as dr
In [2]: dr.set_log_level(dr.LogLevel.Debug)
In [3]: i = dr.detail.reduce_identity(dr.cuda.Float, …
```

Fixed reduce_identity creating intermediate opaque

---

docs/debug.rst

Instead of asking users to find where the ASAN / stdc++ libs are on their platform, you can use gcc to simplify that process
(this may also work for macOS)

Simplify LD_PRELOAD documentation for Linux ASAN debugging

---

src/extra/loop.cpp
tests/test_while_loop.py

When adding the same variable to the loop state twice, the recording algorithm was not able to eliminate that variable from the loop state, even if it was a "loop-invariant state variable".
The reason is that for each occurrence of that variable a separate phi node is created.
When writing those indices back to the C++/Python objects, the variable only gets assigned one of them.
This causes a mismatch between the `inner_in` field and the indices acquired when traversing the C++/Py-tree.
I fixed this by reading back those indices and updating the `inner_in` field directly after writing them to the tree.

Fix loop state aliasing

---

src/extra/loop.cpp
src/python/tracker.cpp
tests/test_while_loop_ad.py

This PR fixes 3 issues with loops.
First, when adding loop state variables to a differentiable `LoopOp`, and some of them do not have gradients attached, the `grad_in_offset` might not correspond to the index in `m_input_indices`.
When indexing into this array using that index an out-of-bounds access occurs.
This is fixed by adding another index `grad_in_index` to the `Input` struct that always tracks the index in `m_input_indices`.
Second, AD-variables that are added to the loop state in a suspended scope, from a opaque C++ object, would not get their AD refcount incremented. It would however be decremented when releasing the temporary state arrays, causing refcounting problems.
Third, this PR enables adding non-initialized variables from the opaque C++ traversal, which is necessary for …

Fixed LoopOp out of bounds read with extra non-grad variables

---

src/python/CMakeLists.txt

As with Mitsuba PR [1317](https://github.com/mitsuba-renderer/mitsuba3/pull/1317), the Dr.Jit stubs were similarly being generated twice on Windows.
Although less frequent, there are examples on the Windows CI of failed builds that appear to be because of race conditions as stub files are attempted to be written into by two independent processes.

Avoid generating stubs twice on Windows

---

src/python/detail.cpp
src/python/docstr.rst
tests/test_detail.py

This adds the missing Python bindings for the Jit scope calls. The motivation for this it to allow users to explicitly separate different Python threads and their CSE.
I added some documentation and a simple test. What remains an open TODO for the future would be to more rigorously document Dr.Jit's thread safety behavior somewhere in the documentation.

Add Python bindings for the jit_scope functions

---

docs/cpp.rst
include/drjit/call.h
tests/call_ext.cpp
tests/test_call_ext.py

The DrJit registry remains untouched, we simply allow instantiating a `CallSupport<Child>` which exposes the interface of  both `Child` and its parent class.

CallSupport: allow calls on derived classes

---

drjit/__init__.py
src/python/docstr.rst
src/python/reduce.cpp
tests/test_reduction.py
tests/test_tensor.py

Changing default behaviour of reductions for tensor types.
To be consistent with past releases, we make `axis=None` for tensor types, and `axis=0` otherwise. A default value of `axis=...` is used to capture this behaviour.
Also move `mean` to cpp implementation

Changing default behaviour of reductions for tensor types.

---

CMakeLists.txt
docs/changelog.rst
docs/reference.rst
drjit/__init__.py
drjit/_reduce.py
include/drjit/array_router.h
include/drjit/autodiff.h
include/drjit/call.h
include/drjit/dynamic.h
include/drjit/extra.h
include/drjit/jit.h
include/drjit/python.h
src/extra/autodiff.cpp
src/extra/loop.cpp
src/python/CMakeLists.txt
src/python/apply.cpp
src/python/docstr.rst
src/python/eval.cpp
src/python/inspect.cpp
src/python/memop.cpp
src/python/print.cpp
src/python/reduce.cpp
src/python/tracker.cpp
tests/if_stmt_ext.cpp
tests/test_autodiff.py
tests/test_memop.py
tests/test_reduction.py

This commit adds the general differentiable prefix reduction operation ``drjit.prefix_reduce()``, which supports arbitrary scalar types, both regular arrays and tensors, and various reduction operations. It is implemented in terms of a blocked prefix reduction for 1D arrays (``drjit.blocked_prefix_reduce()``), which admits arbitrary (non-power-of-two) block sizes. The reductions are efficiently done using shared memory on the CUDA backend.
Most of the changes are in a related Dr.Jit-Core PR https://github.com/mitsuba-renderer/drjit-core/pull/103.
The following two previously existing functions now simply call the general case.
- ``drjit.prefix_sum``
- ``drjit.cumsum``
Somewhat unrelated: the commit removes sanitization-related options from Dr.Jit, since were recently moved to Dr.Jit-Core.

Differentiable prefix reduction

---

include/drjit/array_router.h

For JITArray `set_entry` is needed to write values.

Fix scatter for JIT arrays

---

include/drjit/array_router.h
include/drjit/array_static.h

`select` doesn't quite work when source types are masks:
```cpp
drjit::Packet<float, 16> a, b;
auto m = drjit::select(a > 0, a < b, a > b); // Return type is deduced back to Packet instead of PacketMask
```
And for some compilers this is a straight-up compile error:
```
no matching conversion for static_cast from 'const drjit::PacketMask<float, 16>' to 'ref_cast_t<drjit::PacketMask<float, 16>, E>' (aka 'drji
t::Packet<float, 16>')
```

fix mask type select

---

include/drjit/autodiff.h
include/drjit/extra.h
include/drjit/jit.h
src/extra/autodiff.cpp
src/extra/call.cpp
src/extra/common.h
src/extra/cond.cpp
src/extra/loop.cpp
tests/test_if_stmt.py
tests/test_while_loop.py

Dr.Jit control flow operations (``dr.if_stmt(), drjit.while_loop()``) currently disable gradient tracking of all variable state when the operation takes place within an AD-disabled scope.
This can be surprising when a ``@dr.syntax`` transformation silently passes local variables to such an operation, which then become non-differentiable. @dvicini reported this in issue https://github.com/mitsuba-renderer/drjit/issues/253.
This commit carves out an exception: when variables aren't actually modified by the control flow operation, they can retain their AD identity.
The PR has 3 parts:
- the first commit changes the semantics of ``ad_var_inc_ref`` so that it only does reference counting. The old behavior (drop ref if variable is currently non-differentiable) is moved to a new function …

Improve the behavior of control flow operations (``dr.if_stmt(), drjit.while_loop()``) in AD-suspended scopes

---

src/python/memop.cpp
tests/test_annotations.py
tests/test_memop.py

Motivated by #303 , add support for `gather` and `scatter` when using `dataclass` types

Add support for gather/scatter of dataclass

---

include/drjit/autodiff.h
src/python/autodiff.cpp
tests/test_autodiff.py

This was fixed in prior Dr.Jit release (PR #172). Need to ensure gradients are correctly initialized for all components

Backport fix `dr.backward_from` and `dr.forward_from` on special types

---

include/drjit/call.h

This PR lets users of `DRJIT_CALL_*` macros specify a `domain_` static constexpr method to override the domain name, e.g. based on some of the template parameters.
This is used in this Mitsuba PR: https://github.com/mitsuba-renderer/mitsuba3/pull/1362
If we find an easier way to fix the Mitsuba issue, then this change would no longer be needed.

call_support: allow override of the Domain

---

src/extra/call.cpp
tests/test_call_ext.py

This PR fixes an issue in vectorized calls where the set of side-effects produced by a specific function where attributed to another function. More specifically, this would only happen if the vectorized call was being performed on a domain for which the registry was partially filled (some indices have been freed).
The PR includes a regression test.

Fix incorrect tracking of side-effects per vectorized call target

---

drjit/__init__.py

Fixes the docstring of the Python lerp function. Currently, the argument names and docstring are inconsistent.

Fix documentation of lerp

---

src/extra/autodiff.cpp

`#include <string>` is necessary to allow compiling with
LLVM 20 + libc++.

Add a missing #include <string>

---

include/drjit/array_router.h

This doesn't quite work as intended:
```cpp
using FloatX = drjit::DynamicArray<float>;
using FloatP = drjit::Packet<float, 16>;
drjit::Array<FloatX, 3> v;
drjit::gather<drjit::Array<FloatP, 3>(v, 10); // Should gather indices 10-25 as vector of packets
```

Fix `dr::gather` of non-jit array with scalar indices

---

include/drjit/autodiff.h
include/drjit/extra.h
include/drjit/jit.h
src/extra/autodiff.cpp
tests/CMakeLists.txt
tests/py_cpp_consistency_ext.cpp
tests/test_py_cpp_consistency_ext.py

There are instances where functions that have Python object arguments such as PyTrees use an independent code path relative to just the pure C++ interface. Setting up the test module with initial tests for `tile` and `repeat`, and in the future more tests can be added.

Add `drjit::repeat` for C++ interface. Setting up tests for Python-cpp implementation consistency

---

include/drjit/autodiff.h
include/drjit/call.h
include/drjit/extra.h
include/drjit/jit.h
include/drjit/python.h
src/extra/call.cpp
src/python/switch.cpp
tests/call_ext.cpp

Replaces https://github.com/mitsuba-renderer/drjit/pull/307.
Second attempt at offering a mechanism to isolate symbolic calls, after discussion with @wjakob and @njroussel.
Requires https://github.com/mitsuba-renderer/drjit-core/pull/109 in `drjit-core`.

Call domain isolation per (variant, domain)

---

tests/test_local.py

The actual relevant changes are in `drjit-core`, however we're adding the relevant Python changes here.
These new tests are motivated by fixes for `drjit.Local` when using the `active` mask argument for reads and writes.

Add new local array mask tests. Based on `drjit-core` fixes

---

src/python/apply.cpp
src/python/if_stmt.cpp
src/python/tracker.cpp
src/python/tracker.h
src/python/while_loop.cpp
tests/test_if_stmt.py
tests/test_while_loop.py

This PR updates control flow bindings so that tensors can be used as ``while_loop``/``if_stmt`` condition and state variables.
This feature is convenient when we want to apply element-wise operations with symbolic control flow to a tensor. As before, operations causing inter-component dependencies (slicing, etc.) remain forbidden within the loop body and will raise errors.

Enable the use of tensors in symbolic loops and conditionals

---

include/drjit/texture.h
include/drjit/util.h

Texture channel data is packed contiguously, so leverage PacketOps for gathers (and scatters) that show substantial speed-ups (particularly on the LLVM backend).
This is especially true for half-precision textures, where the absence of FP16 SIMD gather instructions results in bloated compiled kernels and a degradation in performance relative to the single-precision counterpart. PacketOps circumvents this issue by avoiding the use of gather intrinsics entirely.

Add PacketOps support for textures

---

src/extra/call.cpp
tests/test_switch.py

When running AD through evaluated-mode loops, any dynamic dispatch will not have the loop's mask applied.
This PR fixes this issue by saving the loop's mask (top of the mask stack) at the time of tracing the dynamic dispatch into the `CallOp` custom operation. This allows the custom operation to then apply that saved masked whenever it gets traversed.
Without this patch, the issue would typically manifest itself as a CUDA error or segfault during kernel execution. Typically, lanes that should have been masked were accessing out-of-bounds memory.
A regression test was added in `test_switch.py::test18_apply_loop_mask`.

[AD] Fix missing masks on symbolic calls inside loops

---

include/drjit/texture.h

A few Dr.Jit functions in were called using `dr::` in `texture.h`. However, the `dr` namespace alias is not necessarily defined here, and unnecessary. This commit simply removes the namespace qualifier.

Remove unnecessary dr:: in texture.h

---

include/drjit/texture.h
tests/test_annotations.py
tests/test_arithmetic.py

Dr.Jit provides an approximate ``dr.rsqrt()`` operation that performs a reciprocal square root with a very small amount of rounding error (~1 ULP) when compared to the IEEE 754-compliant version. The main benefit is that this has significantly lower latency.
Previously, only the CUDA backend implemented this operation properly, while an IEEE 754-compliant fallback was used on the LLVM backend. This commit adds a proper implementation for AVX, AVX512, and ARM Neon.

Properly compile ``rsqrt`` intrinsic on LLVM

---

include/drjit/autodiff.h
include/drjit/jit.h
include/drjit/python.h

Previously, the Python version of these functions copied a Boolean scalar to the CPU and then constructed a literal array. The new implementation leaves the value on the device and does not block.

Make ``dr.all()``, ``dr.any()``, and ``dr.none()`` asynchronous

---

src/python/docstr.rst
src/python/main.cpp

There can sometimes be lingering issues in a codebase (e.g., forgotten leftovers from a prior debugging session) that trigger costly CPU<->GPU.
The new ``JitFlag.ForbidSynchronization`` flag will raise an exception in ``jitc_sync_thread()`` to immediately identify such problems.

Added ``JitFlag.ForbidSynchronization`` to catch synchronization issues

---

src/python/autodiff.cpp

A prior commit (4d71e9c6e2021e994e03203c3646eabd20fd7b8e) changed CustomOp so that it preserves a copy of variables to remember their size. This has been identified as a source of inefficiency in a downstream application. The change in this PR switches the copy to an empty (jit_var_undefined) array of the right size/type, which does not cause an actual allocation/copy to take place.

CustomOp: avoid an unnecessary variable copy

---

src/python/apply.cpp
src/python/apply.h
src/python/base.cpp
tests/test_arithmetic.py

The ``dr.select()`` operation is able to traverse PyTrees. Whenever encountering unknown object type, it returns ``None`` in its place.
This commit changes the operation so that it preserves the object if both the true/false branch are consistent. Otherwise, it raises an exception.

Better handling of unknown objects in ``dr.select()``

---

docs/types.rst
src/python/init.cpp
tests/test_init.py
tests/test_tensor.py

Dr.Jit can convert between nested arrays and tensors (e.g., ``Array3f(TensorXf(...))`` or ``TensorXf(Array3f(...))``), which requires raveling/unraveling the array contents.
This step preserves the shape -- for example
```
x = dr.zeros(Array3f, shape=(3, N))
y = TensorXf(x)
```
returns a tensor of type ``(3, N)``. However, sometimes what is actually needed is shape ``(N, 3)``.
This PR adds a ``flip_axes`` argument to the constructor that accomplishes this.
```
y = TensorXf(x, flip_axes=True)
y = Array3f(y, flip_axes=True)
```

Ability to flip the order of axes in Tensor -> nested array conversions

---

docs/autodiff.rst
include/drjit/extra.h
src/extra/autodiff.cpp
src/python/autodiff.cpp
src/python/docstr.rst
tests/test_autodiff.py
tests/test_call_ext.py

Prior to this commit, the following operations were simply aliases of each other:
- ``dr.backward_from(x)`` and ``dr.backward(x)``, and
- ``dr.forward_from(x)`` and ``dr.forward(x)``.
They assign an initial gradient to the variable ``x`` and then propagate it. For example, the backwards version expands to:
```
x.grad = 1
dr.enqueue(dr.ADMode.Backward, x)
dr.traverse(dr.ADMode.Backward)
```
However, this behavior is inconvenient when one wants to propagate a specific derivative other than ``1``. It also makes the following functions non-symmetric with respect to each other:
- ``dr.backward_to()`` vs ``dr.backward_from()``
- ``dr.forward_to()`` vs ``dr.forward_from()``
In particular, the ``*_to()`` variants transport existing derivatives *without* the initial assignment.
This PR changes …

Refine the semantics of ``dr.forward_from()`` / ``dr.backward_from()``

---

src/python/docstr.rst

The docs for `kernel_history` state that the reported times are in microseconds but they seem to be in milliseconds.

Minor: Fix time units in `kernel_history` doc

---

src/python/autodiff.cpp
tests/test_autodiff.py

This PR changes the semantics of `dr.replace_grad(a, b)`:
* For non-differentiable types, the function call returns `a` rather than the default initialization. For example, if `a = dr.auto.ad.UInt32(0, 1, 2)` then the function now returns `a` instead of `dr.auto.ad.UInt32()` (zero-width value).
* Non unknown types, it will also just return `a` rather than `None`.
This is helpful for Mitsuba records which are `DRJIT_STRUCT`s, where it would result in a ragged value as non-differentiable members of the struct had width 0. The workaround was to exhaustively call `replace_grad` for each differentiable member.
I don't have a strong opinion on how to handle non-Dr.Jit types, it seemed natural to return the unchanged primal value there too.

`dr.replace_grad`: better handling of non-differentiable types and unknown types

---

docs/reference.rst
drjit/__init__.py
tests/test_tensor.py

The implementation is consistent with NumPy, and we test against it in a new test. It is differentiable and can move multiple axes at once.

Added ``drjit.moveaxis()`` function for rearranging tensor axes

---

src/extra/autodiff.cpp
src/python/meta.cpp
src/python/traits.cpp
tests/test_promote.py

This commit adds a dummy member `VarType::BaseFloat` to the `VarType` enumeration. This type cannot be used for actual computation.
It is a placeholder to be used in situations where we haven't quite decided what floating point precision to assign to a floating point variable (E.g. a Python scalar float).
This allows us to compute things like `Float16(1.0) + 2.0` without the `2.0` being interpreted as `Float32`, causing an unwanted cast to a higher precision.

Added a new `VarType::BaseFloat` for Python type promotion

---

README.rst
docs/autodiff.rst
docs/basics.rst
docs/bench.rst
docs/cflow.rst
docs/changelog.rst
docs/cpp.rst
docs/eval.rst
docs/types.rst
docs/what.rst
drjit/__init__.py
drjit/interop.py
drjit/opt.py
include/drjit/custom.h
include/drjit/math.h
resources/remez.h
src/python/docstr.rst
src/python/reduce.cpp
src/python/tracker.cpp
tests/test_while_loop_ad.py

I went through the v1.0.x docs linearly to update some of my code using drjit v0.4.x. In the process I found a few typos.
This PR only touches documentation.

[doc] Various typo fixes.

---

drjit/dda.py

The `dda()` example in the [API reference](https://drjit.readthedocs.io/en/stable/reference.html#drjit.dda.dda) does not run due to:
* failed type assertions;
* missing parameter in loop function.
This PR updates the example to use the required integer types and function signature.

[dda] Doc fixes

---

docs/type_ref.rst
include/drjit/texture.h
src/python/docstr.rst
src/python/texture.h
tests/test_texture.py

Fix for Mitsuba issue [1493](https://github.com/mitsuba-renderer/mitsuba3/issues/1493). 
Also some minor fix to avoid unnecessarily re-initialising the underlying tensor when updating the value

`texture`: Fix unpadded gradient tracking

---

docs/reference.rst
drjit/__init__.py
include/drjit/resample.h
src/extra/resample.cpp
src/python/resample.cpp
tests/test_resample.py

This PR adds new function ``drjit.convolve()`` that repurposes the ``drjit.resample()`` infrastructure to convolve one or more axes of a Dr.Jit array or tensor with a 1D filter. The user can choose one of multiple presets or specify a custom function.

API to convolve arrays/tensors with continuous convolution kernels

---

include/drjit/python.h
src/python/reduce.cpp
tests/test_init.py
tests/test_reduction.py

This PR fixes #396. In that issue a few different failure cases of `dr.count() were reported`. They were due to missing casts to/from `Bool` types and some missing logic in the main reduction helper function (it would return a boolean rather than an integer if the input type was not a 1D array)..
Test cases were added to check the validity of the new casts and regression tests were added for the configurations brought up in #396.

Minor fixes to `dr.count()`

---

docs/reference.rst
src/python/CMakeLists.txt
src/python/docstr.rst
src/python/main.cpp
src/python/reorder.cpp
src/python/reorder.h
tests/test_reorder.py

This PR adds `dr.reorder_threads()`: an explicit way for users to trigger the SER functionality of their GPU without it being tied to a ray-intersection.
Related: https://github.com/mitsuba-renderer/drjit-core/pull/145
The function takes a `key` argument that acts as the sorting key for the reordering as well as a `value` argument. The latter solely serves a a way for us to tie the operation into the JIT graph.
Because the shuffling happens under the hood, there really isn't a way to test this properly other than a smoke test. I've added some basic ones in a new `test_reorder.py file.

Shader Execution Reordering

---

docs/cpp.rst
docs/reference.rst
drjit/__init__.py
drjit/detail.py
drjit/stubs.pat
include/drjit/call.h
include/drjit/if_stmt.h
include/drjit/sphere.h
src/python/apply.cpp
src/python/freeze.cpp
tests/call_ext.cpp

Currently `mitsuba:master` points to a Dr.Jit version that is slightly ahead of `drjit:master`. Namely, it includes the changes of this commit: https://github.com/mitsuba-renderer/drjit/commit/faa814873ec7f2f7a202538acd2b9b84802aa274. This PR contains that commit and some other minor changes.
Main changes:
- Minor: revived a Python version of the `dr.unit_angle()` function
- Switched to a cleaner API to determine the variant domain/name of a
callable (mainly relevant for Mitsuba). This is now done by querying
the `::Variant` and `::Domain` members  (if present) of the
associated class.
- The `DRJIT_CALL_INHERITED_END()` macro is no longer needed,
`DRJIT_CALL_END()` can be used instead.
- Added an check for the `DRJIT_NO_RTLD_DEEPBIND` environment variable
that was missing in `detail.py`.

Refactor vectorized call APIs

---

include/drjit/python.h
include/drjit/traversable_base.h

The traversal helpers `traverse_py_cb_ro` and `traverse_py_cb_rw` might be called from C++ without holding the GIL. This will typically lead to segfaults. An example of this is the traversal of a custom Mitsuba plugin in a loop's state.
This PR ensures that the GIL is held during those operations.

Hold GIL when traversing python objects

---

docs/reference.rst
include/drjit/array_base.h
include/drjit/array_router.h
include/drjit/array_utils.h
include/drjit/autodiff.h
include/drjit/idiv.h
include/drjit/jit.h
include/drjit/packet_avx2.h
include/drjit/packet_avx512.h
include/drjit/packet_neon.h
include/drjit/packet_recursive.h
include/drjit/packet_sse42.h
include/drjit/python.h
include/drjit/tensor.h
src/python/apply.cpp
src/python/apply.h
src/python/base.cpp
src/python/docstr.rst
tests/test_arithmetic.py

This commit adds the ``dr.mul_wide()`` operation, which performs a wide (e.g. i32 x i32 -> i64) integer multiplication. This is the core operation underlying the Philox pseudorandom number generator.
The commit also exposes ``dr.mul_hi()``, which is similar but only returns the upper part of the result.
They map directly onto the ``mul.wide`` and ``mul.hi`` PTX instructions (or analogous LLVM IR).

Add ``dr.mul_wide()`` wide integer multiplication operation

---

src/python/detail.cpp
tests/test_assert.py

Before this change, enabling DrJit's debug mode could result in crashes due to `std::bad_cast` (`frame.f_lineno == None` could not be cast to `size_t`).
Requires https://github.com/mitsuba-renderer/drjit-core/pull/158 on the drjit-core side.

Debug mode: handle `frame.f_lineno == None` in `trace_func`

---

docs/reference.rst
drjit/__init__.py
include/drjit/tensor.h
tests/test_memop.py

This commit adds the ``dr::take()`` (C++) and ``dr.take()`` (Python) functions inspired by NumPy's ``np.take()``, which efficiently evaluates ``value[..., index, ...]`` (where index is at position 'axis'). 
An additional ``dr::take_interp()`` function takes fractional positions and blends the adjacent tensor slices linearly.

added ``dr::take()`` and ``dr::take_interp()`` functions

---

CMakeLists.txt
docs/basics.rst
docs/coop_vec.rst
docs/nn.rst
docs/reference.rst
docs/type_ref.rst
drjit/__init__.py
drjit/nn.py
drjit/random.py
include/drjit/random.h
include/drjit/traversable_base.h
src/extra/CMakeLists.txt
src/python/CMakeLists.txt
src/python/cuda.cpp
src/python/cuda_ad.cpp
src/python/docstr.rst
src/python/freeze.h
src/python/llvm.cpp
src/python/llvm_ad.cpp
src/python/random.h
src/python/scalar.cpp
tests/call_ext.cpp
tests/conftest.py
tests/test_coop_vec.py
tests/test_freeze.py
tests/test_rand.py

This PR moves the tentative ``dr.rand()`` and ``dr.randn()`` functions into a *generator object* similar to how this works in NumPy and other array APIs. It can be used as follows
```python
rng: dr.random.Generator = dr.rng(seed=123)
value = rng.random(Float, 1000)
value_2 = rng.normal(TensorXf16, shape=(100, 100))
```
Furthermore, the PRNG underlying this interface was switched to a new algorithm named ``Philox4x32``.
This redesign was motivated by the following considerations:
The previously used ``PCG32`` PRNG has very low per-sample cost, but it tends to suffer from correlations between separate parallel streams if not correctly seeded. Another pseudorandom number generator must therefore be added to initialize PCG32 in practice, which increases computational cost and conceptual …

Random number generation API redesign

---

src/python/memop.cpp
tests/test_freeze.py
tests/test_memop.py

This PR updates the drjit-core pointer, and adds a test for the packet scatter reduction operation of f16 values. These will use the `red.global.v2` on `sm_90` or later and the `red.global.add.noftz.f16x2` on `sm_89` or earlier compute capabilities of CUDA.
Depends on: https://github.com/mitsuba-renderer/drjit-core/pull/151

Packet Scatter Reduce tests

---

drjit/opt.py
tests/test_coop_vec.py

This PR expands a test to cover literal gradients for matrix vector multiplications using the new coopvec API, and bumps the drjit-core pointer to the commit fixing this test.

Added gradient literal test

---

src/python/docstr.rst
src/python/main.cpp

This PR adds support for spilling excess registers to shared memory in the CUDA backend.
For more details, see [#160](https://github.com/mitsuba-renderer/drjit-core/pull/160).

Support for excess register spilling to CUDA shared memory

---

src/python/detail.cpp

Python objects bound to C++ classes do not necessarily all have a `__dict__` member. For example, _trampolined_ classes can still be instantiated without them necessarily being a custom Python implementation.
Fixes https://github.com/mitsuba-renderer/mitsuba3/issues/1741

When traversing Python objects, check that `__dict__` exists

---

docs/reference.rst
include/drjit/array_router.h
include/drjit/autodiff.h
include/drjit/jit.h
include/drjit/python.h
src/python/docstr.rst
src/python/memop.cpp
tests/test_memop.py

This PR adds:
* `dr.scatter_exch(target, value, index, active)`: atomically exchange values in an array and return the previous values.
* `dr.scatter_cas(target, compare, value, index, active)`: performs an atomic compare-and-swap operation on array elements.
All of the logic required to implement these operations, are in `drjit-core`: https://github.com/mitsuba-renderer/drjit-core/pull/177
This PR just adds Python bindings, a C++ interface, tests and documentation.

Add `dr.scatter_cas()` and `dr.scatter_exch()`

---

docs/reference.rst
drjit/__init__.py
src/python/docstr.rst
src/python/traits.cpp
tests/test_color.py
tests/test_traits.py

Optimizing colors in RGB space often produces poor visual results because RGB distances don't match human perception. Perceptual color spaces solve this: their distances align with how humans see color differences. Simply switching to a perceptual norm can visibly improve the quality of many algorithms without other changes.
[Oklab](https://bottosson.github.io/posts/oklab/) [Ottosson, 2020] is a perceptual color space designed specifically for image processing. It improves on CIELAB's hue shift problems and HSV's poor perceptual uniformity, while requiring only two 3x3 matrix multiplications and a cube root.
Key properties of Oklab:
- L, a, b coordinates are perceptually orthogonal
- Smooth, uniform color gradients without hue shifts
- Accurate lightness prediction across all hues
- …

Oklab color space conversion
