- resources/generate_stub_files.py
- src/python/CMakeLists.txt
This PR is a follow-up to #49 and @DoeringChristian 's work. 
By default, local builds will now generate python typing information files (stubs).
When building a Python package through scikit-build, the stubs will be included.
> Python typing information (stub generation)

- include/drjit/util.h
- tests/CMakeLists.txt
- tests/dynamic.cpp
- tests/util.cpp
Includes C++ unit tests checked against NumPy.
> Meshgrid: add 3D support on the C++ side

- drjit/router.py
Fixes failing tests because of invalid Python type hints.
> Fix Python type checking in wrap_ad

- tests/python/test_basics.py
> Update drjit-core (remove predicates)

- include/drjit/loop.h
- include/drjit/vcall_jit_record.h
This PR makes Dr.Jit compatible with the following Dr.Jit-Core PRs:
- https://github.com/mitsuba-renderer/drjit-core/pull/40
- https://github.com/mitsuba-renderer/drjit-core/pull/41
> Adapt Dr.Jit to Dr.Jit-Core code generation

- include/drjit/array_base.h
- include/drjit/jit.h
- include/drjit/loop.h
- include/drjit/vcall_jit_record.h
- src/python/main.cpp
- src/python/switch.h
- tests/python/test_simple.py
- tests/texture.cpp
Try running the Dr.Jit test suite with the following Dr.Jit-Core backend changes:
- https://github.com/mitsuba-renderer/drjit-core/pull/51 and
- https://github.com/mitsuba-renderer/drjit-core/pull/52
> Tentative upgrade of Dr.Jit-Core

- include/drjit/packet_intrin.h
To further accommodate diverse platforms and compilers, we would like to use the `tzcnt()` function even when BMI is not supported. However, this can lead to compilation errors:
```
drjit/include/drjit/packet_intrin.h:304:20: error: use of undeclared identifier '_tzcnt_u32'
return (T) _tzcnt_u32((unsigned int) v);
^
drjit/include/drjit/packet_intrin.h:307:20: error: use of undeclared identifier '_tzcnt_u64'
return (T) _tzcnt_u64((unsigned long long) v);
^
2 errors generated.
```
This is because [`_tzcnt_u32/u64` are defined with BMI support](https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set).
This PR introduces a fallback for such scenarios, currently catering to GCC and Clang compilers.
> Expanding tzcnt() compatibility for non-BMI platforms

- include/drjit/array_router.h
- include/drjit/autodiff.h
- include/drjit/fwd.h
- include/drjit/matrix.h
- include/drjit/transform.h
- include/drjit/util.h
Various minor fixes to get Mitsuba compiling
> Some fixes for Mitsuba integration

- drjit/__init__.py
- drjit/detail.py
- src/python/CMakeLists.txt
Previous two commits introduced minor bugs
> Minor fixes to CMake build

- drjit/__init__.py
- tests/test_tensor.py
Based off of original implementation in the prior release
> Add `dr.upsample`

- include/drjit/quaternion.h
This patch fixes minor issues in `dr::quat_to_euler` after the refactoring
> Minor fixes in dr::quat_to_euler

- include/drjit/util.h
This patch fixes the dr::ravel implementation and adds support of `ArrayXf` types.
> Fix dr::ravel and add support for dynamic arrays

- drjit/interop.py
- tests/test_wrap.py
This PR fixes #251.
The gradient values returned by torch will be tensors and they must be set to their respective Dr.Jit output values. The output values must therefore always be tensors, or else the `dr.set_grad` function will fail.
This PR also adds a test when the wrapped function returns a PyTree with a non-tensor member (all existing tests returned tensors or tensors in PyTrees).
> Fix `@dr.wrap` with `torch` sources when the output is not a tensor

- drjit/__init__.py
- tests/test_matrix.py
Need to ensure underlying floating precision is consistent with provided arguments
Fix for #264
> Fix type fetching of some Dr.Jit Python functions

- include/drjit/array_router.h
Extracting the sign bit using comparison operators is not portable across platforms. This commit makes operations like of ``copysign``, ``mulsign``, etc., examine the actual bit pattern.
> Fix the behavior of ``copysign``, ``mulsign``, etc.

- src/python/print.cpp
- tests/test_format.py
In the case that the threadstate mask stack is non-empty, we need to combine the passed in mask with the top of the stack before the compress call.
> `dr.print` : Fix evaluated mode with active mask

- drjit/dda.py
- tests/test_dda.py
This PR addresses three bugs identified in the DDA ray traversal algorithm and introduces corresponding tests. The issues fixed are as follows:
1. **Rays along grid edges (red)**
Rays that pass exactly along the edges of the grid were not handled correctly.
2. **Axis-aligned rays missing the grid (blue)**
Rays aligned with the coordinate axes wrongly intersected the grid.
3. **Rays with negative zero direction (green)**
Rays with a negative zero direction component of -0.0, e.g., $ray_{d4}=\[-1.0,-0.0\]$, were not properly traversed.
- Corrected the ray traversal logic to handle these edge cases.
- Added targeted unit tests to validate each fix and prevent regressions.
The following diagram illustrates the fixed scenarios:
> Fix DDA for rays aligned with grid edges and zero-direction rays

- src/extra/autodiff.cpp
For reasons of ABI compatibility, std::mutex uses a legacy locking API on Windows that is significantly slower than std::shared_mutex.
https://stackoverflow.com/questions/69990339/why-is-stdmutex-so-much-worse-than-stdshared-mutex-in-visual-c
> Use std::shared_mutex in favor of std::mutex on Windows

- tests/test_memop.py
PR for CI run.
Adds a test for https://github.com/mitsuba-renderer/drjit-core/pull/134
> Update drjit-core submodule, add test for `ReduceMode.NoConflicts`

- drjit/opt.py
I have found what I believe to be a discrepancy of Adam's update equation in the documentation.
This PR introduces the necessary corrections.
> Fix typo in Adam's update equation

- src/python/main.cpp
Update drjit-core and nanobind. The latter is to make the nanobind version consistent again between mitsuba & drjit
> Submodule update

- drjit/nn.py
- tests/test_coop_vec.py
- tests/test_freeze.py
\+ add unit test
\+ remove a few unused imports in tests.
> `nn.Linear`: check that the given dtype is a Tensor type

- docs/reference.rst
- src/python/cuda.cpp
- src/python/dlpack.cpp
- src/python/docstr.rst
Depends on https://github.com/mitsuba-renderer/drjit-core/pull/164.
> CUDA: bindings for GL interop

- src/extra/autodiff.cpp
Some compilers complain about the name conflicts between the `Variable` class defined in `autodiff.cpp` and the one defined in `internal.h`. To avoid this, this patch renames the `Variable` class of `autodiff.cpp` into `ADVariable`.
> Rename autodiff.cpp:Variable into ADVariable to avoid conflicts

- include/drjit/autodiff.h
- include/drjit/extra.h
- src/extra/autodiff.cpp
- tests/test_py_cpp_consistency_ext.py
- Fixed interface mismatch for repeat on DiffArray
- Implemented ad_var_repeat and ad_var_tile
> add ad support and fix bug for c++ repeat/tile operations

- src/python/init.cpp
- tests/test_init.py
This is a follow-up to https://github.com/mitsuba-renderer/drjit-core/issues/171.
We generally allow various casts when running `Type(arg)` where `arg` does not have type `Type`. However, we currently do not support cases where the type of `arg` supports automatic differentiation and `Type` doesn't (or the other way around). Effectively casts such as `dr.auto.ad.Float(dr.auto.UInt32(...))` were prohibited. This PR allows such casts.
> Casting Dr.Jit types should be allowed even when a AD<->non-AD conversion is required

- src/python/dlpack.cpp
Previously, Dr.Jit arrays could only be pickled/unpickled through some intermediate route, e.g., by calling ``.numpy()``. This commit adds native support for this.
It also fixes an unrelated issue where nd-array access (through DLPack) could give incorrect results for boolean arrays from the `drjit.scalar.*` module.
> Pickling support

- drjit/opt.py
- tests/test_opt.py
This commit adds an ``AdamW`` optimizer (derived from ``Adam``) with builtin weight decay. The implementation is equivalent to that of PyTorch, which is checked in a new test case.
> Added ``AdamW`` optimizer
